name: asdf

"on":
  push:
  pull_request:

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  osx:
    name: "macOS ${{ matrix.os }}"
    runs-on: "macos-${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os:
          - "14"
          - "15"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Lint
        run: shellcheck mac

      - name: Install legacy ASDF v0.15.0
        run: |
          git clone --branch v0.15.0 https://github.com/asdf-vm/asdf.git ~/.asdf
          echo '. "$HOME/.asdf/asdf.sh"' >> ~/.zshrc
          echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.zshrc
          . "$HOME/.asdf/asdf.sh"
          asdf plugin add act
          asdf install act latest

          echo "PATH=$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH" >> "$GITHUB_ENV"

      - name: Uninstall homebrew
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

      - name: Uninstall apps
        run: |
          rm -Rf \
            "/Applications/1Password.app" \
            "/Applications/Docker.app" \
            "/Applications/Google Chrome.app" \
            "/Applications/iTerm.app" \
            "/Applications/Rectangle.app" \
            "/Applications/Slack.app"

      - name: Test
        run: bash mac
